-- *********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Git Git Git Git Git Git , v3 by alexo+enterprisetest@sqldbm.com *


-- ************************************** Dim_Date
CREATE TABLE Dim_Date
(
 DateId    int NOT NULL,
 Date      datetime NOT NULL,
 Day       int NOT NULL,
 Week      int NOT NULL,
 Month     int NOT NULL,
 Year      int NOT NULL,
 Month_1   int NOT NULL,
 Month_1_1 int NOT NULL,
 Month_1_2 int NOT NULL,
 Month_1_3 int NOT NULL,
 Month_1_4 int NOT NULL,
 CONSTRAINT PK_Dim_Date PRIMARY KEY ( DateId )
)
STAGE_FILE_FORMAT = 
(
 FORMAT_NAME = 'CsvFileFormat'
);
