-- *********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Git Git Git Git Git Git , v3 by alexo+enterprisetest@sqldbm.com *


-- ************************************** Dim_Supplier
CREATE TABLE Dim_Supplier
(
 SupplierId  int NOT NULL,
 CompanyName string NOT NULL,
 Phone       string,
 Phone_1     string,
 Phone_2     string,
 Phone_3     string,
 Phone_4     string,
 Phone_5     string,
 Phone_6     string,
 Phone_7     string,
 Phone_8     string,
 CONSTRAINT PK_Dim_Supplier PRIMARY KEY ( SupplierId )
)
STAGE_FILE_FORMAT = 
(
 FORMAT_NAME = 'CsvFileFormat'
);
