-- ************************************** SqlDBM: Snowflake *************************************
-- * Generated by SqlDBM: Git Git Git Git Git Git , v3 vs v2 by alexo+enterprisetest@sqldbm.com *

ALTER TABLE Dim_Supplier
    ADD COLUMN Phone_1 string;

ALTER TABLE Dim_Supplier
    ADD COLUMN Phone_2 string;

ALTER TABLE Dim_Supplier
    ADD COLUMN Phone_3 string;

ALTER TABLE Dim_Supplier
    ADD COLUMN Phone_4 string;

ALTER TABLE Dim_Supplier
    ADD COLUMN Phone_5 string;

ALTER TABLE Dim_Supplier
    ADD COLUMN Phone_6 string;

ALTER TABLE Dim_Supplier
    ADD COLUMN Phone_7 string;

ALTER TABLE Dim_Supplier
    ADD COLUMN Phone_8 string;

ALTER TABLE Dim_Date
    ADD COLUMN Month_1 int NOT NULL;

ALTER TABLE Dim_Date
    ADD COLUMN Month_1_1 int NOT NULL;

ALTER TABLE Dim_Date
    ADD COLUMN Month_1_2 int NOT NULL;

ALTER TABLE Dim_Date
    ADD COLUMN Month_1_3 int NOT NULL;

ALTER TABLE Dim_Date
    ADD COLUMN Month_1_4 int NOT NULL;