-- *********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Git Git Git Git Git Git , v3 by alexo+enterprisetest@sqldbm.com *


CREATE FILE FORMAT CsvFileFormat
 TYPE = CSV
 COMPRESSION = BROTLI;
